export const BC_LOGO = "/tapps-business-connect-logo.png";

export const categories = [
  {
    slug: "home-services",
    name: "Home Services",
    description:
      "Real estate agents, mortgage, title, landscapers, inspectors, cleaners, staging, junk removal, and more.",
    icon: "🏠",
  },
  {
    slug: "finance-professional",
    name: "Finance & Professional",
    description:
      "Accountants, bookkeepers, financial advisors, insurance, attorneys, consultants, coaching, marketing, IT, and more.",
    icon: "💼",
  },
  {
    slug: "health-wellness",
    name: "Health & Wellness",
    description:
      "Medical, dental, chiropractic, physical therapy, mental health, senior care, nutrition, fitness, massage, and more.",
    icon: "🌿",
  },
  {
    slug: "lifestyle-personal-services",
    name: "Lifestyle & Personal Services",
    description:
      "Beauty, salons, spas, photographers, event planners, travel agents, childcare, pet services, and more.",
    icon: "✨",
  },
  {
    slug: "food-hospitality",
    name: "Food & Hospitality",
    description:
      "Restaurants, catering, coffee, bakeries, breweries, venues, lodging, and more.",
    icon: "🍽️",
  },
  {
    slug: "trades-specialty",
    name: "Trades & Specialty",
    description:
      "Contractors, electricians, plumbers, HVAC, automotive, specialty retail, manufacturing, and more.",
    icon: "🔧",
  },
];

export type Member = {
  slug: string;
  name: string;
  company: string;
  categorySlug: string;
  category: string;
  specialty: string;
  photo: string;
  photos: string[];
  phone: string;
  email?: string;
  website: string;
  facebook: string;
  instagram: string;
  instagramLabel?: string;
  instagram2?: string;
  instagram2Label?: string;
  linkedin: string;
  tiktok: string;
  bio: string;
};

const CDN2 = "https://cdn.prod.website-files.com/67d9e1a205bd4e3c72c4cae0";

function memberPhoto(folder: string, filename: string) {
  return `/memberPhotos/${folder}/${encodeURIComponent(filename)}`;
}

export const allMembers: Member[] = [
  // ── HOME SERVICES ──────────────────────────────────────────────────────────
  {
    slug: "superior-roof-cleaning-jesus-perez",
    name: "Jesus Perez",
    company: "Superior Roof Cleaning",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Roof & Exterior Home Cleaning",
    photo: `${CDN2}/699e0a7afd90b67888825938_286d1851-5a69-41b6-8f13-69504aaca800-2-174887254tbc_formal_headshot-IMG_1657-061346.jpeg`,
    photos: [
      `${CDN2}/699e0a7afd90b67888825938_286d1851-5a69-41b6-8f13-69504aaca800-2-174887254tbc_formal_headshot-IMG_1657-061346.jpeg`,
      `${CDN2}/699e0c1ff1d07a40e006909e_SRCAC%2B10-1920w.webp`,
      `${CDN2}/699e0b6ba0b35f786253fb35_1.jpg`,
    ],
    phone: "253-200-7194",
    website: "https://www.superiorroofcleaningandconstruction.com/",
    facebook: "https://www.facebook.com/share/1FrY4pB9Qb/?mibextid=wwXIfr",
    instagram: "",
    linkedin: "",
    tiktok: "",
    bio: "My name is Jesus Perez, owner of Superior Roof Cleaning & Construction. I proudly serve Pierce County and the surrounding areas, providing professional roof cleaning, exterior cleaning, and specialty services like Christmas light installation. As a local contractor, I understand the unique weather conditions in the Pacific Northwest and how they affect roofs and exterior surfaces. What sets Superior Roof Cleaning & Construction apart is attention to detail, honest communication, and treating every home like it's my own. I focus on long-term results — not quick shortcuts — using safe, proven cleaning methods that protect your roof and extend its life. My goal is simple: deliver high-quality work, show up when I say I will, and make sure every customer feels confident in the investment they made.",
  },
  {
    slug: "andre-bohall-onsite-real-estate-group",
    name: "André Bohall",
    company: "OnSite Real Estate Group",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Real Estate Sales & Purchase | Vacant Land Expert",
    photo: `${CDN2}/68f695d2603b1bd4fc775609_20241213_132625.jpg`,
    photos: [
      `${CDN2}/68f695d2603b1bd4fc775609_20241213_132625.jpg`,
      `${CDN2}/68f7eaabad7790a53fdf21eb_Screenshot_20241118_193345_Messages.jpg`,
      `${CDN2}/695d48df80475536e96b238f_20241213_132554%20(1).jpg`,
    ],
    phone: "253-441-9764",
    website: "https://www.onsiteregroup.com",
    facebook: "https://www.facebook.com/OnSiteREGroup",
    instagram: "https://www.instagram.com/watchmeasirealestate/",
    linkedin: "https://www.linkedin.com/in/onsiteregroup",
    tiktok: "https://www.tiktok.com/@onsiteregroup",
    bio: "With over a decade of experience and hundreds of successful home sales, André Bohall brings deep expertise, tireless dedication, and a personal touch to every real estate journey. As the founder of OnSite Real Estate Group, André leads with service and strategy — combining strong market knowledge with sharp negotiating skills and genuine care for his clients' needs. André is a natural when it comes to sales. His background includes years of high-volume outbound prospecting, phone sales, and client conversion — skills that now translate into powerful results for his buyers and sellers. He understands how to create opportunities where others see roadblocks, and his team is known for delivering results even in competitive markets.",
  },
  {
    slug: "jasmine-guerrero-i-love-carpet-cleaning",
    name: "Jasmine Guerrero",
    company: "I Love Carpet Cleaning",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Carpet, Upholstery & Tile Cleaning",
    photo: `${CDN2}/695d440378be0934dc670cae_916c34da-20ca-4239-9f69-b2ae15115e91-2-174887254tbc_formal_headshot-IMG_3397-394840.jpeg`,
    photos: [
      `${CDN2}/695d440378be0934dc670cae_916c34da-20ca-4239-9f69-b2ae15115e91-2-174887254tbc_formal_headshot-IMG_3397-394840.jpeg`,
      `${CDN2}/695d4456da607f0758b376ee_464.png`,
      `${CDN2}/695d4479c61d8992d178dc6f_916c34da-20ca-4239-9f69-b2ae15115e91-2-174887254marketing_photo_1-IMG_2880-261e9d.jpeg`,
    ],
    phone: "253-861-8098",
    website: "",
    facebook: "https://www.facebook.com/share/1DxHWSXe2i/?mibextid=wwXIfr",
    instagram: "",
    linkedin: "",
    tiktok: "https://www.tiktok.com/@ilovecarpetcleaning253",
    bio: "We are a husband & wife team located in Downtown Puyallup, proudly serving Pierce County as well as parts of King & Thurston counties. Not only is carpet cleaning our specialty, we also offer other cleaning services for upholstery, area rugs, tile & grout. Our clients prefer us for our 'fresh smelling' quality cleaning solutions.",
  },
  {
    slug: "lesa-say-rain-city-capital",
    name: "Lesa Say",
    company: "Rain City Capital",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Real Estate Investor Lending",
    photo: `${CDN2}/695d3f6733a8ccdf54435df2_78646.jpg`,
    photos: [
      `${CDN2}/695d3f6733a8ccdf54435df2_78646.jpg`,
      `${CDN2}/695d40002d58bb47ebb57a41_79646.jpg`,
      `${CDN2}/695d40102d58bb47ebb58814_c963c92d-a6c2-4ef7-943d-0294eed06c01-2-174887254marketing_photo_1-Lesa%20Headshot%201-850b9b.png`,
    ],
    phone: "206-271-8009",
    website: "https://www.raincitycapital.com/",
    facebook: "",
    instagram: "https://www.instagram.com/sayitssold",
    linkedin: "https://www.linkedin.com/in/lesa-say-60a8b162",
    tiktok: "",
    bio: "I'm Lesa Say, Sales Director at Rain City, bringing nearly two decades of experience in real estate as a lender, realtor, and investor. As Rain City's top producer, I've built my career around strong client advocacy and a deep commitment to helping borrowers succeed. Clients know me for being responsive, solution-oriented, and relentless in finding the best path forward — especially when a deal requires creativity or fast problem-solving. I believe in showing up, communicating clearly, and going the extra mile to deliver results that truly make a difference.",
  },
  {
    slug: "eva-armas-ecohaul-solutions",
    name: "Eva Armas",
    company: "EcoHaul Solutions",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Junk Removal",
    photo: `${CDN2}/695d33b0d9216186e149f933_66d1f337-7868-4e1e-8fc1-4a1dbc804294-2-174887254tbc_formal_headshot-Head%20shot%20-%20Eva-83521a.jpg`,
    photos: [
      `${CDN2}/695d33b0d9216186e149f933_66d1f337-7868-4e1e-8fc1-4a1dbc804294-2-174887254tbc_formal_headshot-Head%20shot%20-%20Eva-83521a.jpg`,
      `${CDN2}/695d348ec9beca93ca1a47ca_11.jpg`,
      `${CDN2}/695d34c7328df0e936eac23d_12.jpg`,
    ],
    phone: "253-290-3514",
    website: "https://ecohaulsolutionsllc.com/",
    facebook: "https://www.facebook.com/profile.php?id=61559653257111",
    instagram: "https://www.instagram.com/ehs_junkandhauling/",
    linkedin: "https://www.linkedin.com/company/ecohaul-solutions-junk-hauling/",
    tiktok: "https://www.tiktok.com/@ehs_junkandhauling",
    bio: "EcoHaul Solutions Junk & Hauling LLC is a trusted, local and family operated business proudly serving the Pierce County area with dependable, eco-friendly junk removal services. Owned and operated by a husband and wife team, Edward & Eva. As a locally rooted company, we prioritize honesty, professionalism, and genuine care in every home and business we serve — treating your property with the same respect we would our own. We handle everything from full property cleanouts and commercial jobs to donation pickups and single-item removals. Whether you're a homeowner, business owner, or community partner, you can count on us for professional, reliable service and responsible disposal practices.",
  },
  {
    slug: "alan-dueck-caring-transitions",
    name: "Alan Dueck",
    company: "Caring Transitions",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Senior Relocation | Downsizing | Estate Sales",
    photo: `${CDN2}/6913bee80be78c6f39902360_We%20(3).jpg`,
    photos: [
      `${CDN2}/6913bee80be78c6f39902360_We%20(3).jpg`,
      `${CDN2}/6913be9cfc9f7cdbe8c0cd2e_7.jpg`,
      `${CDN2}/690bc3c6dd7dfb36d4c5a2b5_bb6ac896-9126-4acb-9155-cd28c78972ac-2-174887254marketing_photo_3-Team%20at%20Work%20-%202.png`,
    ],
    phone: "253-286-9950",
    website: "https://www.caringtransitionsofpuyallup.com/",
    facebook: "https://www.facebook.com/CaringTransitionsofPuyallup",
    instagram: "https://www.instagram.com/caringtransitionspuyallup",
    linkedin: "https://www.linkedin.com/company/caring-transitions-of-puyallup-and-auburn-wa",
    tiktok: "",
    bio: "Caring Transitions helps older adults and their families throughout Puyallup, Auburn, Bonney Lake and surrounding areas navigate life's transitions with compassion and care. Whether it's a senior move, estate sale, or a complete cleanout, we manage the entire process from start to finish — so families don't have to do it alone. Our certified team handles sorting, packing, online auctions, and move coordination with the utmost respect for your loved ones and their belongings.",
  },
  {
    slug: "devin-quinn-evergreen-home-loans",
    name: "Devin Quinn",
    company: "Evergreen Home Loans",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Home Loans, NMLS 1305012",
    photo: `${CDN2}/68f664bed96a3bd392189a14_devin-quinn-puyallup-wa-loan-officer-evergreen-home-loans.webp`,
    photos: [
      `${CDN2}/68f664bed96a3bd392189a14_devin-quinn-puyallup-wa-loan-officer-evergreen-home-loans.webp`,
      `${CDN2}/68fa95ad213faf394a088667_We%20(2).jpg`,
    ],
    phone: "253-278-9192",
    website: "https://www.evergreenhomeloans.com/loan-officers/devin-quinn",
    facebook: "https://www.facebook.com/devinquinn1305012",
    instagram: "https://www.instagram.com/devinjq84/",
    linkedin: "https://www.linkedin.com/in/devinjamesquinn/",
    tiktok: "",
    bio: "Devin Quinn, NMLS 1305012, Evergreen Home Loans. I truly believe in loving the work you do. It is a privilege to help families finance the purchase of their new home. Whether you're a first-time buyer, a seasoned investor, or navigating the challenges of today's market, I'm here to guide you with honesty and expertise. I focus on education, communication, and transparency — making sure every client understands their options every step of the way.",
  },

  // ── FINANCE & PROFESSIONAL ─────────────────────────────────────────────────
  {
    slug: "kevin-barquest-insurance-alliance",
    name: "Kevin Barquest",
    company: "Insurance Alliance",
    categorySlug: "finance-professional",
    category: "Finance & Professional",
    specialty: "Business & Commercial Insurance",
    photo: `${CDN2}/695d381093c6855cd1122592_222.jpg`,
    photos: [
      `${CDN2}/695d381093c6855cd1122592_222.jpg`,
      `${CDN2}/695d385f93c6855cd1123aa9_66c18c8e-30cc-46f1-b376-d9f8ecafc34f-2-174887254business_logo-IA%20Flag%20Logo-3f3d30.png`,
      `${CDN2}/695d38709dc5df8f8aaa8d17_66c18c8e-30cc-46f1-b376-d9f8ecafc34f-2-174887254marketing_photo_2-Kevin%20Biz%20Card-f854a6.png`,
    ],
    phone: "253-642-4010",
    website: "https://www.theinsalliance.com/",
    facebook: "https://www.facebook.com/insurancealliancellc",
    instagram: "https://www.instagram.com/insurancealliancellc",
    linkedin: "https://linkedin.com/company/insurancealliancellc",
    tiktok: "",
    bio: "Kevin Barquest is the owner of Insurance Alliance LLC, an independent insurance agency dedicated to putting clients first. As an independent agency, we work with multiple carriers to find the best coverage at the best price — not just the best option from one company. Kevin specializes in business and commercial insurance, helping entrepreneurs and business owners protect what they've built with comprehensive, tailored coverage solutions.",
  },
  {
    slug: "anna-jacobson-insurance-alliance",
    name: "Anna Jacobson",
    company: "Insurance Alliance",
    categorySlug: "finance-professional",
    category: "Finance & Professional",
    specialty: "Residential & Personal Insurance",
    photo: `${CDN2}/695d366078be0934dc633646_a618b0cb-1d02-4a44-9f04-ffa933625df9-2-174887254tbc_formal_headshot-IA%20Flag%20Logo-522434.png`,
    photos: [
      `${CDN2}/695d366078be0934dc633646_a618b0cb-1d02-4a44-9f04-ffa933625df9-2-174887254tbc_formal_headshot-IA%20Flag%20Logo-522434.png`,
      `${CDN2}/695d36c1742925db3dbef97b_a618b0cb-1d02-4a44-9f04-ffa933625df9-2-174887254marketing_photo_1-Disaster%20Insurance-c8f62d.png`,
      `${CDN2}/695d36c99dc5df8f8aaa446d_a618b0cb-1d02-4a44-9f04-ffa933625df9-2-174887254marketing_photo_2-Home%20Insurance-fd5268.png`,
    ],
    phone: "253-642-4010",
    website: "https://www.theinsalliance.com/",
    facebook: "https://www.facebook.com/insurancealliancellc",
    instagram: "https://www.instagram.com/insurancealliancellc",
    linkedin: "https://www.linkedin.com/company/insurancealliancellc",
    tiktok: "",
    bio: "Anna Jacobson is a personal lines insurance specialist with Insurance Alliance LLC, helping clients find the right coverage for their homes, autos, and personal assets. With a focus on education and advocacy, Anna helps clients understand what their policies actually cover — and ensures there are no surprises when they need to file a claim. She's passionate about protecting families and making insurance simple and accessible.",
  },
  {
    slug: "brittany-guempel-wafd-bank",
    name: "Brittany Guempel",
    company: "WaFd Bank",
    categorySlug: "finance-professional",
    category: "Finance & Professional",
    specialty: "Personal, Business, and Commercial Banking",
    photo: `${CDN2}/6913b74424e1668065e8eb4b_b1.png`,
    photos: [
      `${CDN2}/6913b74424e1668065e8eb4b_b1.png`,
      `${CDN2}/6913b65c62552a8dac7fc4a5_We%20(1).jpg`,
      `${CDN2}/6913b736f3e8512b490eae21_We%20(2).jpg`,
    ],
    phone: "253-441-9764",
    website: "https://wafdbank.com",
    facebook: "",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/brittany-guempel/",
    tiktok: "",
    bio: "WaFd Bank is proud to serve small towns and big cities in nine western states. For more than 100 years, WaFd Bank has been a stable, community-focused financial partner. Brittany Guempel brings personalized banking solutions for individuals, small businesses, and commercial clients — offering checking, savings, loans, and business banking products tailored to the Pacific Northwest community.",
  },
  {
    slug: "gina-humphries-ameriprise-financial",
    name: "Gina Humphries",
    company: "Ameriprise Financial Services, LLC",
    categorySlug: "finance-professional",
    category: "Finance & Professional",
    specialty: "Financial Advisor",
    photo: `${CDN2}/690bc1c628edc4863747c911_0283a1b1-1676-4d05-a80e-e5e2d9fd0a83-2-174887254tbc_formal_headshot-Gina%20headshot%20july2025.jpg`,
    photos: [
      `${CDN2}/690bc1c628edc4863747c911_0283a1b1-1676-4d05-a80e-e5e2d9fd0a83-2-174887254tbc_formal_headshot-Gina%20headshot%20july2025.jpg`,
      memberPhoto("ginaHumphries", "AMPF_Logo_2026_w.png"),
    ],
    phone: "206-310-2272",
    email: "Gina.Humphries@ampf.com",
    website: "https://www.ameripriseadvisors.com/gina.humphries/?awsrc=namematch",
    facebook: "",
    instagram: "",
    linkedin: "",
    tiktok: "",
    bio: "Hello, my name is Gina Humphries, and I am a Financial Advisor in Bonney Lake with Ameriprise Financial. I believe financial planning should be personal, purposeful, and grounded in a deep understanding of what matters most to you. I work with individuals and families to build long-term investment strategies, plan for retirement, and protect what they've worked hard to build — with the support of Ameriprise Financial's resources and my commitment to personal service.",
  },
  {
    slug: "kim-campbell-campbell-tax-accounting",
    name: "Kim Campbell",
    company: "Campbell Tax & Accounting, LLC",
    categorySlug: "finance-professional",
    category: "Finance & Professional",
    specialty: "Business Tax & Accounting",
    photo: `${CDN2}/68f6844194f20db1cb7bc95c_1733497756463.jpg`,
    photos: [
      `${CDN2}/68f6844194f20db1cb7bc95c_1733497756463.jpg`,
      `${CDN2}/68ffbfae55b89c50195aee09_Campbell%20Logo.png`,
      `${CDN2}/68ffc320ce0d0027d467c6e1_1.png`,
    ],
    phone: "253-397-0836",
    website: "https://www.campbelltaxandaccounting.com",
    facebook: "https://www.facebook.com/camptaxacct",
    instagram: "",
    linkedin: "",
    tiktok: "",
    bio: "We're a Bonney Lake-based CPA firm that partners with local business owners to simplify their accounting, minimize taxes, and maximize their financial success. At Campbell Tax & Accounting, we don't just prepare returns — we provide year-round strategic guidance so you can focus on growing your business with confidence. Kim Campbell brings deep expertise in small business taxation, bookkeeping, and financial planning tailored to the Pacific Northwest business community.",
  },

  // ── TRADES & SPECIALTY ─────────────────────────────────────────────────────
  {
    slug: "jnkelectric",
    name: "JNKElectric",
    company: "JNKElectric",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Residential & Commercial Electric",
    photo: `${CDN2}/69a5ee4230a42914a844dbc3_DSC02011-scaled-e1767926193988.jpg`,
    photos: [
      `${CDN2}/69a5ee4230a42914a844dbc3_DSC02011-scaled-e1767926193988.jpg`,
      `${CDN2}/69a5f0351399f10a17c239d7_TBC%20Website%20Photo%20Resize.png`,
      `${CDN2}/69a5ee1af7697502c3630058_2.jpg`,
    ],
    phone: "253-553-1046",
    website: "https://jnkelectrical.com/",
    facebook: "https://www.facebook.com/profile.php?id=61553014245608",
    instagram: "",
    linkedin: "",
    tiktok: "",
    bio: "Our founders, Jeff and Kevin, started JNK Electrical Solutions after years of working side-by-side in the industry — driven by a shared belief that clients deserve honest, quality electrical work without the runaround. Whether it's residential service upgrades, panel replacements, or commercial electrical projects, JNKElectric brings professionalism and integrity to every job in Pierce County and surrounding areas.",
  },
  {
    slug: "jimmy-alekseenko-simple-floor-solutions",
    name: "Jimmy Alekseenko",
    company: "Simple Floor Solutions",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Flooring Company",
    photo: `${CDN2}/695d3abd7664d0d0238090bf_03ca7982-f824-4462-9644-530f33348dbe-2-174887254tbc_formal_headshot-IMG_3163-2fee44.jpeg`,
    photos: [
      `${CDN2}/695d3abd7664d0d0238090bf_03ca7982-f824-4462-9644-530f33348dbe-2-174887254tbc_formal_headshot-IMG_3163-2fee44.jpeg`,
      `${CDN2}/695d3afd47d1734db909fd14_03ca7982-f824-4462-9644-530f33348dbe-2-174887254business_logo-Official%20Logo%204-757006.png`,
      `${CDN2}/695d3b2dc624fa4226a5161c_464.jpg`,
    ],
    phone: "253-316-5886",
    website: "https://simplefloorsolutions.com/",
    facebook: "https://www.facebook.com/share/1aQMcukaxu/?mibextid=wwXIfr",
    instagram: "https://www.instagram.com/simplefloorsolutions",
    linkedin: "",
    tiktok: "",
    bio: "Jimmy Alekseenko is the founder & owner of Simple Floor Solutions, a family-run flooring company built on quality craftsmanship and exceptional customer service. From hardwood and luxury vinyl to tile and carpet, Jimmy and his team deliver flawless installations that transform spaces and stand the test of time. Based in Pierce County, Simple Floor Solutions is known for reliability, attention to detail, and doing it right every time.",
  },
  {
    slug: "travis-ohlde-maxcare-of-washington",
    name: "Travis Ohlde",
    company: "MaxCare of Washington",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Home Restoration",
    photo: `${CDN2}/695d397030f92d09a9c5005f_4986.jpg`,
    photos: [
      `${CDN2}/695d397030f92d09a9c5005f_4986.jpg`,
      `${CDN2}/695d39fec9beca93ca1e25c1_8e22371c-6bf8-4bd7-8b01-fe56c70cb489-2-174887254business_logo-MaxCARE_Logo_RGB-321ccd.jpg`,
      `${CDN2}/695d39d79dc5df8f8aaab041_96.jpg`,
    ],
    phone: "253-223-8228",
    website: "https://maxcare247.com/",
    facebook: "https://www.facebook.com/people/MaxCare-of-Washington-INC/61566166307982/",
    instagram: "",
    linkedin: "https://www.linkedin.com/company/maxcare-of-washington",
    tiktok: "",
    bio: "At MaxCare of Washington, restoration is more than just fixing buildings — it's about helping people put their lives back together. As a first-generation, family-owned company with a three-decade legacy, we've stood beside families and businesses during some of their hardest moments. When disaster strikes, you don't just need repairs. You need someone you can trust to guide you through the process. With more than 300 years of combined team experience, we understand what insurance companies need and how to advocate for our clients every step of the way.",
  },
  {
    slug: "crystal-waltz-flow-tech-heating-air",
    name: "Crystal Waltz",
    company: "Flow Tech Heating & Air",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Residential Heating & Air",
    photo: `${CDN2}/6913a968dc00d445bf94ea01_17e6f1dc-607a-4037-909f-4e4e96912674-2-174887254tbc_formal_headshot-Pic%201.jpeg`,
    photos: [
      `${CDN2}/6913a968dc00d445bf94ea01_17e6f1dc-607a-4037-909f-4e4e96912674-2-174887254tbc_formal_headshot-Pic%201.jpeg`,
      `${CDN2}/6913a9e9e6d30a80de91fba9_17e6f1dc-607a-4037-909f-4e4e96912674-2-174887254marketing_photo_1-Mike%20Pic%202.jpeg`,
      `${CDN2}/6913aa04aac344548660d397_17e6f1dc-607a-4037-909f-4e4e96912674-2-174887254marketing_photo_3-2%20Ton_%20AH%20install%20Pic%202.jpg`,
    ],
    phone: "253-448-0801",
    website: "https://www.flowtechheatingac.com",
    facebook: "https://www.facebook.com/FlowTechHeatingACAndElectric",
    instagram: "https://www.instagram.com/flowtech0081/",
    linkedin: "https://www.linkedin.com/in/crystal-waltz-982812264/",
    tiktok: "https://www.tiktok.com/@crystal.waltz0",
    bio: "Flow Tech Heating AC & Electric is a family owned and operated business committed to delivering exceptional heating, air conditioning, and electrical services. We proudly serve Pierce County, Lewis County, Thurston County, and South King County. What distinguishes us is our upfront pricing fostering transparency in our services. We believe in treating our customers like family, cultivating trust and loyalty that lasts a lifetime.",
  },
  {
    slug: "pat-wheeler-trustworthy-roofing",
    name: "Pat Wheeler",
    company: "Trustworthy Roofing",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Residential Roofing",
    photo: `${CDN2}/68fbbcbec8156f7f7f23a730_8bf89298-8f95-4f08-8073-3d5819866293-2-174887254tbc_formal_headshot-IMG_0003.jpeg`,
    photos: [
      `${CDN2}/68fbbcbec8156f7f7f23a730_8bf89298-8f95-4f08-8073-3d5819866293-2-174887254tbc_formal_headshot-IMG_0003.jpeg`,
      `${CDN2}/68fbbd39c1be912599c2348b_8bf89298-8f95-4f08-8073-3d5819866293-2-174887254business_logo-Trustworthy%20Roofing%20Logo.png`,
      `${CDN2}/68f7fdd8f316858653b63ede_Screenshot%202025-10-21%20143834.jpg`,
    ],
    phone: "253-455-4347",
    website: "https://trustworthy-construction.com/",
    facebook: "https://www.facebook.com/people/Trustworthy-Construction/61552847915718/",
    instagram: "https://www.instagram.com/trustworthyconstruction/",
    linkedin: "https://www.linkedin.com/in/trustworthy-roofing-1a455a393",
    tiktok: "https://www.tiktok.com/@trustworthyconstruction",
    bio: "Trustworthy Roofing cares about YOU — the people we are putting a roof over! We serve the greater Puget Sound area: Pierce, King, Snohomish, Thurston Counties and more. We raise the standard by only doing what's right and best in our work. We deliver exceptional service to our customers, never cutting corners and always giving high quality results. We have fair pricing, are transparent and our local roofing team has been specializing in roofing for 30+ years. You can trust us to put the roof over your head!",
  },
  {
    slug: "justin-schulke-black-pearl-painters",
    name: "Justin Schulke",
    company: "Black Pearl Painters",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Residential & Commercial Painters",
    photo: `${CDN2}/69a5ec0cacaf60c99e62a8ee_Justin%20Profile%20(1).jpg`,
    photos: [
      `${CDN2}/69a5ec0cacaf60c99e62a8ee_Justin%20Profile%20(1).jpg`,
      `${CDN2}/699dcfa8524979b0a5c3542c_TBC%20Website%20Photo%20Resize%20(1).jpg`,
      `${CDN2}/68f7f12b2a7fe8c78ef84cb1_DJI_0844-1-scaled.webp`,
    ],
    phone: "253-203-5335",
    website: "https://blackpearlpainters.com/",
    facebook: "https://www.facebook.com/BlackPearlPainters",
    instagram: "https://www.instagram.com/blackpearlpainters",
    linkedin: "https://www.linkedin.com/company/black-pearl-painters/",
    tiktok: "",
    bio: "Founded and led by Justin Schulke and Kellie Myler, Black Pearl Painters proudly serves the Puget Sound area, specializing in premium residential and commercial painting. From Bonney Lake and Gig Harbor to the surrounding communities, we've built our reputation on precision, professionalism, customer service, and a commitment to excellence that goes beyond the brush. Our team is known for clear communication, clean worksites, punctuality, and long-lasting finishes that protect and beautify your investment.",
  },
  {
    slug: "matt-cahill-eikon-homes",
    name: "Matt Cahill",
    company: "Eikon Homes",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Home Design & Remodeling | Outdoor Living Spaces",
    photo: `${CDN2}/68f68d91b383464654ef5103_df39a1ed-06d1-49f7-ae1d-60c309fe4c65-2-174887254tbc_formal_headshot-IMG_1831.jpg`,
    photos: [
      `${CDN2}/68f68d91b383464654ef5103_df39a1ed-06d1-49f7-ae1d-60c309fe4c65-2-174887254tbc_formal_headshot-IMG_1831.jpg`,
      `${CDN2}/68f68f1369542760ee04d09e_df39a1ed-06d1-49f7-ae1d-60c309fe4c65-2-174887254business_logo-IMG_7410%202.jpg`,
      `${CDN2}/68f68f4f165d77d68ce80007_Truck-Wrap.webp`,
    ],
    phone: "253-300-6644",
    website: "https://www.eikonhomes.com/",
    facebook: "https://www.facebook.com/Eikonhomes/",
    instagram: "https://www.instagram.com/eikon_homes/",
    linkedin: "",
    tiktok: "",
    bio: "Eikon Homes is the South Sound's premier full-service design & build contractor. We're not just builders — we're craftsmen, creators, and partners in bringing your vision to life. Every project is designed with precision, built with integrity, and managed with care from start to finish. Our clients choose Eikon Homes because we deliver a luxury-level remodeling experience — combining transparent communication, meticulous cleanliness practices, and flawless attention to detail.",
  },
  {
    slug: "andrew-knudsen-myfence",
    name: "Andrew Knudsen",
    company: "MyFence.com",
    categorySlug: "trades-specialty",
    category: "Trades & Specialty",
    specialty: "Fence Contracting | Fence Genius Build Process",
    photo: memberPhoto("andrewKnudsen", "andrewKnudsenPhoto.jpeg"),
    photos: [
      memberPhoto("andrewKnudsen", "andrewKnudsenPhoto.jpeg"),
      memberPhoto("andrewKnudsen", "14670eab-5daa-4e56-a6ca-62b589b7cf95-2-174887254business_logo-MyFence.com Logo-2f926b.png"),
      memberPhoto("andrewKnudsen", "14670eab-5daa-4e56-a6ca-62b589b7cf95-2-174887254marketing_photo_1-Craftsman Style Board on Board Fence-0d702a.png"),
      memberPhoto("andrewKnudsen", "14670eab-5daa-4e56-a6ca-62b589b7cf95-2-174887254marketing_photo_2-MyFence.com 1080x1080 1-36441a.png"),
      memberPhoto("andrewKnudsen", "14670eab-5daa-4e56-a6ca-62b589b7cf95-2-174887254marketing_photo_3-MyFence.com Software and Actual 3-bb9ce6.png"),
    ],
    phone: "253-298-8646",
    website: "https://myfence.com/",
    facebook: "https://www.facebook.com/myfence.com.official",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/andrew-knudsen-70a16118b/",
    tiktok: "https://www.tiktok.com/@myfence.com",
    bio: "We are your local fence contracting company MyFence.com. We serve from Orting to Bothell and have a one-of-one fence construction approach through a new advanced fence construction method via Fence Genius, enabling total customer clarity and near-perfect quality through our patented build process.",
  },

  // ── FOOD & HOSPITALITY ─────────────────────────────────────────────────────
  {
    slug: "stephanie-jensen-coffee-vault",
    name: "Stephanie Jensen",
    company: "Coffee Vault & Lake Tapps Society",
    categorySlug: "food-hospitality",
    category: "Food & Hospitality",
    specialty: "Coffee, Snacks & Local Community Hospitality",
    photo: memberPhoto("stephanieJensen", "stephanieJensenPhoto.jpeg"),
    photos: [
      memberPhoto("stephanieJensen", "stephanieJensenPhoto.jpeg"),
      memberPhoto("stephanieJensen", "3c7ff229-036b-43db-a9bc-142d91974669-2-174887254business_logo-image0-42a054.jpeg"),
      memberPhoto("stephanieJensen", "3c7ff229-036b-43db-a9bc-142d91974669-2-174887254marketing_photo_1-IMG_3489_jpg-273cd5.jpeg"),
      memberPhoto("stephanieJensen", "3c7ff229-036b-43db-a9bc-142d91974669-2-174887254marketing_photo_2-IMG_6055_jpg-cc68ff.jpeg"),
      memberPhoto("stephanieJensen", "3c7ff229-036b-43db-a9bc-142d91974669-2-174887254marketing_photo_3-IMG_6693_jpg-85db39.jpeg"),
    ],
    phone: "253-224-7015",
    website: "https://coffeevaultco.com/",
    facebook: "",
    instagram: "https://www.instagram.com/coffeevault_co/",
    instagramLabel: "Coffee Vault",
    instagram2: "https://www.instagram.com/thelaketappssociety/",
    instagram2Label: "Lake Tapps Society",
    linkedin: "",
    tiktok: "",
    bio: "At Coffee Vault and The Lake Tapps Society, we strive to provide high quality drinks, snacks and service coupled with a comfortable experience that highlights and supports everything that makes Lake Tapps and our local community so special!",
  },

  // ── HEALTH & WELLNESS ────────────────────────────────────────────────────────
  {
    slug: "amanda-matthews-precision-and-grace-aesthetics",
    name: "Amanda Matthews",
    company: "Precision and Grace Aesthetics",
    categorySlug: "health-wellness",
    category: "Health & Wellness",
    specialty: "Medical Aesthetics & Wellness | Neurotoxins, Filler & IV Therapy",
    photo: memberPhoto("amandaMathews", "amandaMathewsPhoto.png"),
    photos: [
      memberPhoto("amandaMathews", "amandaMathewsPhoto.png"),
      memberPhoto("amandaMathews", "2d6eb89f-04af-4534-a113-15e97e6d00f6-2-174887254business_logo-Precision and Grace Logo with white background-3825c5.png"),
      memberPhoto("amandaMathews", "2d6eb89f-04af-4534-a113-15e97e6d00f6-2-174887254marketing_photo_2-Untitled design-5014b2.png"),
      memberPhoto("amandaMathews", "2d6eb89f-04af-4534-a113-15e97e6d00f6-2-174887254marketing_photo_3-IMG_7581-b66172.jpg"),
    ],
    phone: "253-961-1528",
    website: "https://www.precisionandgrace.com/",
    facebook: "https://www.facebook.com/profile.php?id=61587930846434",
    instagram: "https://www.instagram.com/precision_and_grace/",
    linkedin: "",
    tiktok: "",
    bio: "Rooted in Anatomy. Refined with Grace. Where clinical precision meets refined aesthetics. Precision and Grace Aesthetics is an anatomy-led aesthetic and wellness practice founded and led by Amanda Matthews, ARNP. We offer personalized treatments including neurotoxins, dermal filler, microneedling, chemical peels, and IV therapy. Our approach is grounded in safety, integrity, and education, enhancing your natural features while supporting wellness from within. We believe in refining, not redefining, and creating results that feel balanced and uniquely you. Whether you walk in dressed up or straight from the gym, you are welcomed as you are. Proudly serving Pierce County with locations in Bonney Lake and Puyallup, we are committed to helping you feel confident and supported at every stage of life.",
  },
  {
    slug: "stephanie-lyman-welling-health",
    name: "Stephanie Lyman",
    company: "Welling Health",
    categorySlug: "health-wellness",
    category: "Health & Wellness",
    specialty: "Telehealth | Metabolic Health & Hormone Optimization",
    photo: memberPhoto("stephanieLyman", "stephanieLymanPhoto.png"),
    photos: [
      memberPhoto("stephanieLyman", "stephanieLymanPhoto.png"),
      memberPhoto("stephanieLyman", "97c29599-6e4e-4976-9316-2c1ae4424d75-2-174887254business_logo-image-6ce461.png"),
      memberPhoto("stephanieLyman", "97c29599-6e4e-4976-9316-2c1ae4424d75-2-174887254marketing_photo_1-ChatGPT Image Apr 3, 2026 at 11_21_51 AM-3bbbbb.png"),
      memberPhoto("stephanieLyman", "97c29599-6e4e-4976-9316-2c1ae4424d75-2-174887254marketing_photo_2-Screenshot 2026-05-11 123911-aab906.jpg"),
      memberPhoto("stephanieLyman", "97c29599-6e4e-4976-9316-2c1ae4424d75-2-174887254marketing_photo_3-Screenshot 2026-05-11 124018-8357a3.jpg"),
    ],
    phone: "619-496-6318",
    website: "https://wellinghealth.com/",
    facebook: "",
    instagram: "https://www.instagram.com/well_ing_health",
    linkedin: "",
    tiktok: "",
    bio: "Welling is a Washington based telehealth wellness practice founded by Stephanie Lyman, ARNP, FNP BC, focused on individualized metabolic health, sustainable weight management, and hormone optimization. Serving patients across Washington State, Welling takes a \"low and slow\" approach to care, emphasizing precision dosing, long term success, body composition preservation, and patient education. What makes Welling different is the highly personalized support, collaborative care model, and focus on helping patients better understand their bodies through evidence based treatment, nutrition guidance, lifestyle support, and advanced tools like GLP-1 therapy, DEXA analysis, and hormone focused care.",
  },

  // ── NEW HOME SERVICES MEMBERS ──────────────────────────────────────────────
  {
    slug: "dekota-bramsche-rpm-today",
    name: "Dekota Bramsche",
    company: "RPM Today | Property Management",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Residential & Commercial Property Management",
    photo: memberPhoto("dekotaBramsche", "dekotaBramsche.jpg"),
    photos: [
      memberPhoto("dekotaBramsche", "dekotaBramsche.jpg"),
      memberPhoto("dekotaBramsche", "ef14ec2b-dcc9-416c-ab5b-097b74242bae-2-174887254business_logo-RPMLOGO-4e103a.png"),
      memberPhoto("dekotaBramsche", "ef14ec2b-dcc9-416c-ab5b-097b74242bae-2-174887254marketing_photo_1-Beach RPM-05b88e.jpg"),
      memberPhoto("dekotaBramsche", "ef14ec2b-dcc9-416c-ab5b-097b74242bae-2-174887254marketing_photo_2-The One RPM-f97c89.jpg"),
      memberPhoto("dekotaBramsche", "ef14ec2b-dcc9-416c-ab5b-097b74242bae-2-174887254marketing_photo_3-Puyallup SFH-89df47.jpg"),
    ],
    phone: "253-625-6902",
    website: "https://rpmtoday.com/",
    facebook: "",
    instagram: "https://www.instagram.com/rpmtoday/",
    linkedin: "https://www.linkedin.com/in/dekota-bramsche-8160522a4",
    tiktok: "",
    bio: "My name is Dekota Bramsche and I'm the Business Development Manager at Real Property Management Today. We focus on delivering reliable, full-service property management that protects our clients' investments while creating high-quality homes for residents. We take pride in ensuring every property is managed with attention to detail, clear communication, and a proactive approach. At RPM Today, we understand that successful property management is about more than just collecting rent — it's about maximizing long-term value. We handle everything from tenant placement and maintenance to financial oversight and compliance, all with the goal of reducing risk and improving performance for owners. At the same time, we believe residents deserve well-maintained, comfortable homes. By balancing owner priorities with resident satisfaction, we help reduce turnover, protect property condition, and build stronger communities. We serve Pierce County, Kitsap County, Southern King County, and North Thurston County.",
  },
  {
    slug: "becky-barringer-barringer-design-studio",
    name: "Becky Barringer",
    company: "Barringer Design Studio",
    categorySlug: "home-services",
    category: "Home Services",
    specialty: "Interior Design | Remodels & New Construction",
    photo: memberPhoto("beckyBerringer", "beckyBarringerPhoto.jpeg"),
    photos: [
      memberPhoto("beckyBerringer", "beckyBarringerPhoto.jpeg"),
      memberPhoto("beckyBerringer", "10a9a8a6-0935-4e0d-adb9-0501d0bd23e6-2-174887254business_logo-Barringer Design Studio Logo-bdca26.png"),
      memberPhoto("beckyBerringer", "10a9a8a6-0935-4e0d-adb9-0501d0bd23e6-2-174887254marketing_photo_1-IMG_8166-02c17a.jpg"),
      memberPhoto("beckyBerringer", "10a9a8a6-0935-4e0d-adb9-0501d0bd23e6-2-174887254marketing_photo_2-Floor Detail-bc618b.jpg"),
      memberPhoto("beckyBerringer", "10a9a8a6-0935-4e0d-adb9-0501d0bd23e6-2-174887254marketing_photo_3-IMG_8042-124686.jpg"),
    ],
    phone: "253-380-8398",
    website: "https://www.barringerdesignstudio.com/",
    facebook: "",
    instagram: "https://www.instagram.com/barringer_design_studio",
    linkedin: "",
    tiktok: "",
    bio: "Barringer Design Studio is a full-service interior design studio specializing in home furnishings, remodels, and new construction in the South Puget Sound area and beyond. Through our thoughtful, proven design process, we guide each project from initial concept to final walkthrough with care, clarity, and intention. At BDS, great design is about more than beautiful finishes. It's about creating spaces that flow well, function effortlessly, and make everyday life feel easier and more enjoyable. We partner with homeowners who value a well-organized, intentional approach to remodeling and furnishing their homes — one rooted in trust, clarity, and thoughtful decision-making. We take the time to understand your style, how you live, and what you want your home to do for you — then thoughtfully curate a design that feels both elevated and deeply functional. Our goal is to make the entire experience feel seamless, refined, and as stress-free as possible.",
  },

  // ── NEW FINANCE & PROFESSIONAL MEMBERS ─────────────────────────────────────
  {
    slug: "lyndsy-vasquez-odegard-law",
    name: "Lyndsy Vasquez",
    company: "Odegard Law",
    categorySlug: "finance-professional",
    category: "Finance & Professional",
    specialty: "Personal Injury Law",
    photo: memberPhoto("odegardLaw", "lyndsyVasquezPhoto.jpeg"),
    photos: [
      memberPhoto("odegardLaw", "lyndsyVasquezPhoto.jpeg"),
      memberPhoto("odegardLaw", "638428d1-05f7-4c3f-9dbc-8d8ff1ba1314-2-174887254business_logo-IMG_0010-9ce2e6.jpeg"),
      memberPhoto("odegardLaw", "638428d1-05f7-4c3f-9dbc-8d8ff1ba1314-2-174887254marketing_photo_1-IMG_1194-20b6e3.jpeg"),
      memberPhoto("odegardLaw", "638428d1-05f7-4c3f-9dbc-8d8ff1ba1314-2-174887254marketing_photo_2-8A70A9A8-5BB4-4EE8-B2D5-E6CEA6A211F7-1d7377.png"),
      memberPhoto("odegardLaw", "638428d1-05f7-4c3f-9dbc-8d8ff1ba1314-2-174887254marketing_photo_3-9277EF39-118D-4D2D-BD6F-E81C91CCEDF6-f31c70.png"),
    ],
    phone: "253-293-8349",
    website: "https://odegardlawfirm.com/",
    facebook: "https://www.facebook.com/share/1B8AtMuQ7q/?mibextid=wwXIfr",
    instagram: "https://www.instagram.com/odegardlegal",
    linkedin: "",
    tiktok: "",
    bio: "At Odegard Law, we are more than just a personal injury firm — we are advocates for our community. We believe every client deserves honesty, communication, and a team that truly fights for their best interests. While many firms focus on volume, we focus on results, relationships, and real advocacy. Our mission is simple: protect our clients, stand by them from start to finish, and deliver the strong representation they deserve.",
  },
  {
    slug: "chelsea-scott-nelson-allen-walk-scott",
    name: "Chelsea Scott",
    company: "Nelson Allen Walk & Scott, PLLC",
    categorySlug: "finance-professional",
    category: "Finance & Professional",
    specialty: "Attorney",
    photo: memberPhoto("chelseaScott", "chelseaScottPhoto.jpg"),
    photos: [
      memberPhoto("chelseaScott", "chelseaScottPhoto.jpg"),
      memberPhoto("chelseaScott", "86510775-6d1c-436a-b427-1c7b3e94151e-2-174887254business_logo-Logo-a90f13.jpg"),
      memberPhoto("chelseaScott", "86510775-6d1c-436a-b427-1c7b3e94151e-2-174887254marketing_photo_1-689016632_1456221909638600_8574337162739636533_n-40a3a1.jpg"),
      memberPhoto("chelseaScott", "86510775-6d1c-436a-b427-1c7b3e94151e-2-174887254marketing_photo_3-Office-6cb51d.jpg"),
    ],
    phone: "253-224-7019",
    email: "chelsea@nawslaw.com",
    website: "https://nawslaw.com/",
    facebook: "https://www.facebook.com/nelsonallenwalk",
    instagram: "",
    linkedin: "",
    tiktok: "",
    bio: "Nelson Allen Walk & Scott, PLLC is a trusted Pacific Northwest law firm proudly serving communities throughout the greater Puget Sound region. Our attorneys provide strategic, client-focused representation in family law, real estate, estate planning, business law, civil litigation, and personal injury cases. What sets our firm apart is our combination of deep local roots, extensive courtroom and transactional experience, and a commitment to personalized service. We understand that every client's situation is unique, and we take pride in delivering practical solutions, responsive communication, and compassionate advocacy while fiercely protecting our clients' interests.",
  },

];

// Helpers
export const members: Record<string, Member[]> = {
  "home-services": allMembers.filter((m) => m.categorySlug === "home-services"),
  "finance-professional": allMembers.filter((m) => m.categorySlug === "finance-professional"),
  "trades-specialty": allMembers.filter((m) => m.categorySlug === "trades-specialty"),
  "lifestyle-personal-services": allMembers.filter((m) => m.categorySlug === "lifestyle-personal-services"),
  "food-hospitality": allMembers.filter((m) => m.categorySlug === "food-hospitality"),
  "health-wellness": allMembers.filter((m) => m.categorySlug === "health-wellness"),
};

export const membersBySlug: Record<string, Member> = Object.fromEntries(
  allMembers.map((m) => [m.slug, m])
);
